// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxpyljkifompcggqhyri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4cHlsamtpZm9tcGNnZ3FoeXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2ODQxOTgsImV4cCI6MjA5MDI2MDE5OH0.8rd43gNYSsyggKPkt433Zqi1OX0wCKhzbxojdhH_Lbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});