// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbumhvobevmqciyyvgty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNidW1odm9iZXZtcWNpeXl2Z3R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3NDcwMTcsImV4cCI6MjA5MDMyMzAxN30.fyvok14qiozSck6KBnlC3iwYWXB50yOa61s5PrgXbEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});